### ISSUE TITLE
测试apk 注册了帐号无法登录

### ISSUE THREAD

**Issue by tianshaokai** [jiangzehui/xmpp#2]
并不像qq 一样 注册后生成一个 类似qq 的帐号 用于登录

**Comment by jiangzehui** [comment]
你好，是手机注册成功后，无法登陆么？还是。。。另外说一下 QQ 或者微博每次都得授权才可以登陆的

**Comment by tianshaokai** [comment]
手机号 注册的 无法登录，，我没有用qq 或 微博 第三方登录

**Comment by yogkin** [comment]
是否少了个lib的文件夹没有上传？

**Comment by jiangzehui** [comment]
已发现问题，晚上回去修复，谢谢反馈！

**Comment by jiangzehui** [comment]
所有问题都已修复，谢谢反馈！！
