### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by zhengzhi530** [jiangzehui/xmpp#4]
试了一下，手机注册的时候就手机短信可以收到，但是设置密码就报网络错误。QQ授权也无法登陆，是不是服务器挂了呢？

**Comment by jiangzehui** [comment]
我刚试了一下，没有问题。

**Comment by zhengzhi530** [comment]
我是在百度应用市场下载的apk，换换看，谢谢你提供的开源项目，对学习很有用

**Comment by jiangzehui** [comment]
https://github.com/jiangzehui/xmpp/blob/master/apk/yyq1.2.2.apk
